title: Download Canon Printer Driver - Wireless Connectivity
description: Canon.com/ijsetup and enter your printer model number to download the software. Install on your device and follow the given steps.
theme: jekyll-theme-cayman
